title: "Oracle Designer Toolkit Terraform"
description: "A terraform script to deploy Oracle Designer Toolkit using Resource Manager and Freetier resources"
schemaVersion: 1.0.1
version: "20200527"
locale: "en"

groupings:
  - title: "General Configuration"
    visible: false
    variables:
      - compartment_ocid

variables:
  compartment_ocid:
    type: oci:identity:compartment:id
    # type: string
    required: true
    title: "Compartment"
    description: "The compartment in which to create compute instance"

outputGroups:
  - title: "Okit App details"
    outputs:
      - ${Okit_url}
      - ${Okit_url2}
      - ${dev}
      - ${comments}

outputs:
  Okit_url:
    type: link
    title: Open
    visible: true

  Okit_url2:
    type: link
    title: "Okit URL"
    visible: true

  dev:
    type: string
    title: "Message"
    displayText: "Made with \u2764 by Fabio Silva"
    visible: true

  comments:
    type: string
    title: "Comments"
    displayText: "The application URL will be unavailable for a few minutes after provisioning, while the application is configured"
    visible: true

primaryOutputButton: ${Okit_url}